#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SCREEN_WIDTH 1200
#define SCREEN_HEIGHT 600

#define PANEL_WIDTH 300
#define STATUS_BAR_HEIGHT 30

#define CANVAS_WIDTH (SCREEN_WIDTH - PANEL_WIDTH)
#define CANVAS_HEIGHT (SCREEN_HEIGHT - STATUS_BAR_HEIGHT)

#define VERTEX_RADIUS 20
#define EDGE_WIDTH 5

#define ANCHOR_FORCE_MAG 0.08
#define VELOCITY_DAMPENING 0.98
#define VELOCITY_CAP 1500.0f

#endif
