#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SCREEN_WIDTH 1200
#define SCREEN_HEIGHT 600

#define PANEL_WIDTH 200
#define STATUS_BAR_HEIGHT 20

#define CANVAS_WIDTH (SCREEN_WIDTH - PANEL_WIDTH)
#define CANVAS_HEIGHT (SCREEN_HEIGHT - STATUS_BAR_HEIGHT)

#define VERTEX_RADIUS 20

#endif
