#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SCREEN_WIDTH 1200
#define SCREEN_HEIGHT 600

#define PANEL_WIDTH 300
#define STATUS_BAR_HEIGHT 30

#define VERTEX_RADIUS 20
#define EDGE_WIDTH 5

#define ANCHOR_FORCE_MAG 0.08
#define TEMPERATURE_DECAY 0.99
#define INITIAL_TEMPERATURE 1000.0f
#define VELOCITY_CAP 1500.0f

#endif
