name: Test Dijkstra Algorithm

on:
  push:
    branches: [ "main"] 
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install GCC
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: compile test
      run: |
        make tests

    - name: test logics
      run: |
        for test in test-*.out; do
          echo "Executing $test..."
          ./$test || exit 1
          echo "$test passed"
        done
